# Generated by Django 3.2.12 on 2022-05-31 21:13

import carshare.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(db_column='location', max_length=250)),
                ('year', models.IntegerField(default=1, max_length=4)),
                ('make', models.CharField(choices=[('Selected', 'Selected'), ('honda', 'HONDA'), ('toyota', 'TOYOTA'), ('jeep', 'JEEP')], default='Selected', max_length=50)),
                ('model', models.CharField(choices=[('Selected', 'Selected'), ('Honda', (('SUV & Crossovers', 'SUV & CROSSOVERS'), ('Sedans', 'SEDANS'), ('Hatchbacks', 'HATCHBACKS'), ('Minivans', 'MINIVANS'))), ('Toyota', (('Corolla', 'COROLLA'), ('Avalon', 'AVALON'), ('Prius', 'PRIUS'))), ('Jeep', (('SUV', 'SUV'), ('Trucks', 'TRUCKS')))], default='Selected', max_length=50)),
                ('transmission', models.CharField(choices=[('Selected', 'Selected'), ('Manual', 'MANUAL'), ('Automatic', 'AUTOMATIC')], default='Selected', max_length=50)),
                ('odometer', models.CharField(choices=[('Selected', 'Selected'), ('0-50k miles', '0-50K MILES'), ('50k-100k miles', '50-100K MILES'), ('100k-130k miles', '100K-130K MILES'), ('130k+ miles', '130K+ MILES')], default='Selected', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(choices=[('Advance notice', 'Advance notice'), ('1 hour', '1 HOUR'), ('2 hours', '2 HOURS'), ('3 hours', '3 HOURS'), ('6 hours', '6 HOURS'), ('12 hours', '12 HOURS'), ('1 day', '1 DAY'), ('2 days', '2 DAYS'), ('3 days', '3 DAYS'), ('1 week', '1 WEEK')], default='Advance notice', max_length=50)),
                ('shortest_possible_duration', models.CharField(choices=[('Minimum duration', 'Minimum duration'), ('Any', 'Any'), ('1 day', '1 day'), ('2 days', '2 days'), ('3 days', '3 days'), ('5 days', '5 days'), ('1 week', '1 week'), ('2 weeks', '2 weeks'), ('1 month', '1 month')], default='Minimum duration', max_length=50)),
                ('longest_possible_duration', models.CharField(choices=[('Maximum duration', 'Maximum duration'), ('3 days', '3 days'), ('5 days', '5 days'), ('1 week', '1 week'), ('2 weeks', '2 weeks'), ('1 month', '1 month'), ('3 months', '3 months'), ('Any', 'Any')], default='Maximum duration', max_length=50)),
                ('about_car', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_car', to='carshare.aboutcar')),
            ],
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(default='', max_length=7)),
                ('state_or_province', models.CharField(choices=[('State', (('California', 'California'), ('Florida', 'Florida'), ('Minnesota', 'Minnesota'), ('New Jersey', 'New Jersey'), ('New York', 'New York'))), ('Province', (('Alberta', 'Alberta'), ('Ontario', 'Ontario'), ('Quebec', 'Quebec')))], default='State or Province', max_length=50)),
                ('car_description', models.CharField(default='', max_length=250)),
                ('ev_hybrid', models.BooleanField(default=False)),
                ('bike_rack', models.BooleanField(default=False)),
                ('all_wheel_drive', models.BooleanField(default=False)),
                ('child_seat', models.BooleanField(default=False)),
                ('snow_tires_or_chains', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('ski_rack', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('usb_input', models.BooleanField(default=False)),
                ('heated_seats', models.BooleanField(default=False)),
                ('audio_input', models.BooleanField(default=False)),
                ('convertible', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('toll_pass', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('car_availability', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_availability', to='carshare.caravailability')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='test_image.jpg', upload_to=carshare.models.upload_to, verbose_name='Image')),
                ('car_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_details', to='carshare.cardetail')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListCarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_listing_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_car', to='carshare.carphoto')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, null=True)),
                ('year', models.IntegerField(default=1, max_length=4)),
                ('rating', models.IntegerField(default=1, max_length=4)),
                ('trips', models.IntegerField(default=0, max_length=3)),
                ('safety_check', models.BooleanField(default=False)),
                ('free_delivery', models.BooleanField(default=False)),
                ('cost', models.IntegerField(default=0, max_length=3)),
                ('image', models.ImageField(default='test_image.jpg', upload_to=carshare.models.upload_to, verbose_name='Image')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='carshare.category')),
            ],
        ),
    ]
