# Generated by Django 3.2.12 on 2022-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, null=True)),
                ('year', models.IntegerField(default=1, max_length=4)),
                ('rating', models.IntegerField(default=1, max_length=4)),
                ('trips', models.IntegerField(default=0, max_length=3)),
                ('safetyCheck', models.BooleanField(default=False)),
                ('freeDelivery', models.BooleanField(default=False)),
                ('cost', models.IntegerField(default=0, max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
